name: Deploy on Push

on:
  push:
    branches:
      - main

jobs:
  manual-task:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ${{ secrets.OCI_USER }}
          key: ${{ secrets.OCI_SSH_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            export MONGO_URI="${{ secrets.MONGO_URI }}"
            export BOT_TOKEN="${{ secrets.BOT_TOKEN }}"
            export clientId="${{ secrets.DISCORD_CLIENT_ID }}"
            export guildId="${{ secrets.DISCORD_GUILD_ID }}"
            cd FunLabBot
            git pull origin main
            npm install
            node scripts/guild-deploy-commands.js
            pm2 restart FunLabBot --update-env