name: Manual Deploy

on:
  workflow_dispatch:

jobs:
  manual-task:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ${{ secrets.OCI_USER }}
          key: ${{ secrets.OCI_SSH_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            cd FunLabBot
            git pull origin main
            node -v
            npm -v
            npm install
            node scripts/guild-deploy-commands.js
            pm2 restart FunLabBot

            